site_name: Collection 3165 - ABCD-BIDS Community Collection (ABCC)
theme: readthedocs
plugins:
  - search
docs_dir: docs
pages:
  - Table of Contents: index.md
  - 1. Release Notes: release_notes.md
  - 2. Inputs: inputs.md
  - 3. Pipeline: pipeline.md
  - 4. Derivatives: derivatives.md
  - 5. Recommendations: recommendations.md
  - 6. Useful Links: useful.md
