site_name: ABCC Archival Data Release Documentation
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Home: index.md
  - Release Notes: release_notes.md
  - Inputs: inputs.md
  - Pipeline: pipelines.md
  - Post Pipeline: postpipeline.md
  - Derivatives: derivatives.md
  - Recommendations: recommendations.md
  - Useful Links: useful.md
