site_name: Collection 3165 - ABCD-BIDS Community Collection (ABCC)
theme: readthedocs
plugins:
  - search
docs_dir: docs
pages:
  - Home: index.md
  - 1. Release Notes: release_notes.md
  - 2. Inputs: inputs.md
  - 3. Pipeline: pipeline.md
  - 4. Post Pipeline: postpipeline.md
  - 5. Derivatives: derivatives.md
  - 6. Recommendations: recommendations.md
  - 7. Useful Links: useful.md
